create index if not exists idx_tournaments_status_created on public.tournaments(status, created_at desc);
create index if not exists idx_teams_tournament on public.teams(tournament_id, active);
create index if not exists idx_teams_profile on public.teams(profile_id);
create index if not exists idx_matches_tournament_played on public.matches(tournament_id, played_at desc, created_at desc);
create index if not exists idx_matches_home_team on public.matches(home_team_id);
create index if not exists idx_matches_away_team on public.matches(away_team_id);
create index if not exists idx_ownership_team on public.player_ownership(tournament_id, team_id, for_sale);
create index if not exists idx_player_stats_rank on public.player_stats(tournament_id, goals desc, red_cards asc);
create index if not exists idx_trade_offers_status on public.trade_offers(tournament_id, status, updated_at desc);
create index if not exists idx_trade_offers_player on public.trade_offers(tournament_id, player_id);
create index if not exists idx_transfers_tournament_created on public.transfers(tournament_id, created_at desc);
create index if not exists idx_financial_team_created on public.financial_transactions(tournament_id, team_id, created_at desc);
create index if not exists idx_reviews_status_updated on public.player_reviews(status, updated_at desc);
create index if not exists idx_favorites_profile on public.profile_favorites(tournament_id, profile_id);
create index if not exists idx_sync_events_revision on public.sync_events(revision desc);
create index if not exists idx_operation_journal_tournament on public.operation_journal(tournament_id, created_at desc);
